# Generated by Django 2.2.13 on 2020-06-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_cventry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cventry',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cventry',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
