# Generated by Django 2.2.13 on 2020-06-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200617_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cventry',
            name='end_date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cventry',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cventry',
            name='start_date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cventry',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cventry',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
