# Generated by Django 2.2.13 on 2020-06-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200617_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='cventry',
            name='section',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
