# Generated by Django 2.2.13 on 2020-06-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_cventry_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='cventry',
            name='section',
            field=models.CharField(default='Introduction', max_length=200),
            preserve_default=False,
        ),
    ]
