# Generated by Django 2.2.13 on 2020-06-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_cventry_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cventry',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
